// Google Gemini AI Client for Content Generation

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1'
// Use v1 API with gemini-2.5-flash model (latest stable version)
const GEMINI_MODEL = 'gemini-2.5-flash'

export interface GeneratePostOptions {
  topic?: string
  tone?: 'professional' | 'casual' | 'inspirational' | 'educational'
  length?: 'short' | 'medium' | 'long'
  includeHashtags?: boolean
  includeEmojis?: boolean
}

export class GeminiClient {
  private apiKey: string

  constructor(apiKey: string) {
    this.apiKey = apiKey
  }

  // Helper method to retry API calls with exponential backoff
  private async retryWithBackoff<T>(
    fn: () => Promise<T>,
    maxRetries: number = 3,
    initialDelay: number = 1000
  ): Promise<T> {
    let lastError: any
    
    for (let attempt = 0; attempt < maxRetries; attempt++) {
      try {
        return await fn()
      } catch (error: any) {
        lastError = error
        
        // Check if error is retryable (rate limit, overload, etc.)
        const isRetryable = 
          error.message.includes('overloaded') ||
          error.message.includes('429') ||
          error.message.includes('503') ||
          error.message.includes('rate limit')
        
        if (!isRetryable || attempt === maxRetries - 1) {
          throw error
        }
        
        // Exponential backoff: wait longer each time
        const delay = initialDelay * Math.pow(2, attempt)
        console.log(`Retry attempt ${attempt + 1}/${maxRetries} after ${delay}ms...`)
        await new Promise(resolve => setTimeout(resolve, delay))
      }
    }
    
    throw lastError
  }

  // Generate a LinkedIn post
  async generatePost(options: GeneratePostOptions = {}): Promise<string> {
    const {
      topic = 'professional development',
      tone = 'professional',
      length = 'medium',
      includeHashtags = true,
      includeEmojis = false,
    } = options

    const prompt = this.buildPrompt(topic, tone, length, includeHashtags, includeEmojis)

    return this.retryWithBackoff(async () => {
      const response = await fetch(
        `${GEMINI_API_BASE}/models/${GEMINI_MODEL}:generateContent?key=${this.apiKey}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  {
                    text: prompt,
                  },
                ],
              },
            ],
            generationConfig: {
              temperature: 0.8, // Slightly higher for more creative but still focused content
              topK: 40,
              topP: 0.9, // Lower for more focused, less random outputs
              maxOutputTokens: 2048, // Increased to allow longer posts
              candidateCount: 1, // Generate only one candidate for consistency
            },
            safetySettings: [
              {
                category: "HARM_CATEGORY_HARASSMENT",
                threshold: "BLOCK_NONE"
              },
              {
                category: "HARM_CATEGORY_HATE_SPEECH",
                threshold: "BLOCK_NONE"
              },
              {
                category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
                threshold: "BLOCK_NONE"
              },
              {
                category: "HARM_CATEGORY_DANGEROUS_CONTENT",
                threshold: "BLOCK_NONE"
              }
            ],
          }),
        }
      )

      if (!response.ok) {
        const errorText = await response.text()
        console.error('Gemini API Response:', errorText)
        
        let errorData
        try {
          errorData = JSON.parse(errorText)
        } catch {
          throw new Error(`Gemini API Error: ${response.status} - ${errorText}`)
        }
        
        const errorMessage = errorData.error?.message || `HTTP ${response.status}: ${response.statusText}`
        throw new Error(`Gemini API Error: ${errorMessage}`)
      }

      const data = await response.json()
      
      console.log('✅ Gemini API Response received')
      console.log('📦 Full Response Data:', JSON.stringify(data, null, 2))
      
      // Check for prompt feedback (blocking)
      if (data.promptFeedback) {
        console.log('📋 Prompt Feedback:', data.promptFeedback)
        if (data.promptFeedback.blockReason) {
          console.error('🚫 Content was BLOCKED:', data.promptFeedback.blockReason)
          throw new Error(`Content blocked by AI safety filters: ${data.promptFeedback.blockReason}. Please try a different topic.`)
        }
      }
      
      if (!data.candidates || data.candidates.length === 0) {
        console.error('❌ No candidates in response')
        console.error('Full response:', JSON.stringify(data, null, 2))
        throw new Error('No content generated by AI. Please try again with a different topic.')
      }

      console.log('📊 Number of candidates:', data.candidates.length)
      console.log('🔍 Candidate data:', JSON.stringify(data.candidates[0], null, 2))
      
      // Check finish reason
      const finishReason = data.candidates[0]?.finishReason
      console.log('🏁 Finish Reason:', finishReason)
      
      if (finishReason === 'SAFETY') {
        console.error('🚫 Content was blocked by safety filters')
        console.error('Safety ratings:', data.candidates[0]?.safetyRatings)
        throw new Error('Content was blocked by AI safety filters. Please try a different topic or tone.')
      }
      
      if (finishReason === 'MAX_TOKENS') {
        console.warn('⚠️ Response was truncated due to max tokens limit')
      }

      const generatedText = data.candidates[0]?.content?.parts[0]?.text

      if (!generatedText) {
        console.error('❌ Empty text in response')
        console.error('Candidate structure:', JSON.stringify(data.candidates[0], null, 2))
        throw new Error('Empty response from AI. Please try again.')
      }

      console.log('📝 Generated content length:', generatedText.length, 'characters')
      console.log('📄 First 200 chars:', generatedText.substring(0, 200))
      console.log('📄 Last 200 chars:', generatedText.substring(Math.max(0, generatedText.length - 200)))
      
      return generatedText.trim()
    })
  }

  // Generate multiple post variations
  async generatePostVariations(
    topic: string,
    count: number = 3
  ): Promise<string[]> {
    const posts: string[] = []

    for (let i = 0; i < count; i++) {
      const tone = ['professional', 'casual', 'inspirational'][i % 3] as any
      const post = await this.generatePost({ topic, tone })
      posts.push(post)
    }

    return posts
  }

  // Improve/rewrite an existing post
  async improvePost(originalPost: string): Promise<string> {
    const prompt = `You are a LinkedIn content expert. Improve the following LinkedIn post to make it more engaging, professional, and likely to get high engagement. Keep the core message but enhance the writing, structure, and impact.

Original post:
${originalPost}

Improved post:`

    return this.retryWithBackoff(async () => {
      const response = await fetch(
      `${GEMINI_API_BASE}/models/${GEMINI_MODEL}:generateContent?key=${this.apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: prompt,
                },
              ],
            },
          ],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 1024,
          },
        }),
      }
    )

    if (!response.ok) {
      const errorText = await response.text()
      console.error('Gemini API Error:', errorText)
      throw new Error(`Failed to improve post: ${response.status} - ${errorText}`)
    }

      const data = await response.json()
      return data.candidates[0]?.content?.parts[0]?.text.trim()
    })
  }

  // Generate post ideas based on topic
  async generatePostIdeas(topic: string, count: number = 5): Promise<string[]> {
    const prompt = `Generate ${count} engaging LinkedIn post ideas about "${topic}". Each idea should be a brief one-sentence description of what the post would be about. Make them diverse and interesting.

Format: Return only the ideas, one per line, numbered.`

    return this.retryWithBackoff(async () => {
      const response = await fetch(
      `${GEMINI_API_BASE}/models/${GEMINI_MODEL}:generateContent?key=${this.apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: prompt,
                },
              ],
            },
          ],
        }),
      }
    )

    if (!response.ok) {
      const errorText = await response.text()
      console.error('Gemini API Error:', errorText)
      throw new Error(`Failed to generate ideas: ${response.status} - ${errorText}`)
    }

      const data = await response.json()
      const text = data.candidates[0]?.content?.parts[0]?.text
      
      // Parse the numbered list
      const ideas = text
        .split('\n')
        .filter((line: string) => line.trim())
        .map((line: string) => line.replace(/^\d+\.\s*/, '').trim())

      return ideas
    })
  }

  // Build the prompt for post generation
  private buildPrompt(
    topic: string,
    tone: string,
    length: string,
    includeHashtags: boolean,
    includeEmojis: boolean
  ): string {
    const lengthGuide = {
      short: '100-150 words (2-3 short paragraphs)',
      medium: '150-250 words (3-4 paragraphs)',
      long: '250-400 words (5-6 paragraphs)',
    }

    const toneGuide = {
      professional: 'Use professional, authoritative language. Focus on insights, data, and expertise. Write like a thought leader or industry expert.',
      casual: 'Use conversational, friendly language. Write like you\'re talking to a colleague over coffee. Be relatable and approachable.',
      inspirational: 'Use motivating, uplifting language. Share stories, lessons learned, and encourage action. Be authentic and passionate.',
      educational: 'Use clear, informative language. Break down complex topics. Teach something valuable. Use examples and explanations.',
    }

    let prompt = `You are an expert LinkedIn content creator with 10+ years of experience creating viral posts.

TOPIC: "${topic}"

CRITICAL INSTRUCTIONS - FOLLOW EXACTLY:
1. Write SPECIFICALLY about the topic provided above. Do NOT write about generic topics.
2. If the topic mentions specific details, technologies, companies, or concepts - YOU MUST include them in the post.
3. The content must be directly relevant to what the user asked for.
4. Tone: ${tone} - ${toneGuide[tone as keyof typeof toneGuide]}
5. Length: ${lengthGuide[length as keyof typeof lengthGuide]}
6. Structure:
   - Start with a compelling hook (question, bold statement, or surprising fact)
   - Use short paragraphs (2-3 lines max) for readability
   - Add line breaks between paragraphs
   - Include specific examples or insights related to the topic
   - End with a clear call-to-action or thought-provoking question`

    // Always include emojis for better engagement
    prompt += '\n7. Use 3-5 relevant emojis throughout the post:'
    prompt += '\n   - Add 1-2 emojis at the very beginning to grab attention'
    prompt += '\n   - Sprinkle 2-3 emojis within the content to emphasize key points'
    prompt += '\n   - Choose emojis that match the topic and tone'
    prompt += '\n   - Examples: 💡 for ideas, 🚀 for growth, 💪 for motivation, 📊 for data, ✨ for success'

    if (includeHashtags) {
      prompt += '\n8. End with 3-5 highly relevant hashtags that match the specific topic'
    }

    prompt += `

IMPORTANT: 
- Stay focused on the exact topic: "${topic}"
- Make it authentic and valuable
- Write in first person when appropriate
- Be specific, not generic
- If the topic mentions a specific industry, technology, or concept, make sure to discuss it in detail

Write the LinkedIn post now (ONLY the post content, no explanations):`

    return prompt
  }
}

// Helper function to create client
export function createGeminiClient(): GeminiClient {
  // Get API key from environment (server-side only)
  const apiKey = process.env.GOOGLE_AI_API_KEY
  
  console.log('🤖 Creating Gemini Client')
  console.log('🔑 API Key Status:', apiKey ? `Present (${apiKey.substring(0, 10)}...)` : '❌ MISSING')
  
  if (!apiKey) {
    console.error('❌ GOOGLE_AI_API_KEY is not configured in environment variables!')
    throw new Error('GOOGLE_AI_API_KEY is not configured')
  }

  return new GeminiClient(apiKey)
}
